### ISSUE TITLE
Windows Version possible?

### ISSUE THREAD

**Issue by adueck** [ZeptByteS/dvorak-qwerty#2]
Would you be able to make this for Windows 10? 

This is exactly what I (and many others probably) want, but I can't find one that works.

Thanks so much!

**Comment by jcnauta** [comment]
@adueck on Windows 10 the best way I've found is to use AutoHotKey with the script from here: https://autohotkey.com/board/topic/25093-mac-style-dvorak-qwerty-command-layout-switcher-for-windows/. It could be a good idea for the devs to support Windows though :)

**Comment by brandonforster** [comment]
I use this repo for Windows:

github.com/chid/dvorak-qwerty
