### ISSUE TITLE
Is it an alternative to swap the CapsLock key function?

### ISSUE THREAD

**Issue by lotc** [ZeptByteS/dvorak-qwerty#3]
Hi there,
I'm using dvorak layout as default. Every time I switch input method, it will roll back to qwerty.
Is there possible to make `CapsLock Off` is dvorak while `CapsLock On` is qwerty?
Much thanks.

**Comment by ZeptByteS** [comment]
Hi,
CapsLock Off means Shift-Level is 1 or 2. These levels are needed for Qwerty hot keys.

How about that use Scroll Lock to switch between Dvorak and Qwerty?
https://github.com/ZeptByteS/dvorak-qwerty/tree/ScrollLock_to_switch
note that there are no dead-keys in this case.

**Comment by lotc** [comment]
Thanks, I'll take a try.
